name: build-feather
on:
  push:
    paths:
      - 'firmware/**'
      - '.github/workflows/build-feather.yml'
  workflow_dispatch:
defaults:
  run:
    shell: bash --noprofile --norc -x -e -o pipefail {0}
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - name: Install compiler, libraries and tools
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib srecord
      - name: Build Jarvis C0 Feather RP2040 USB Host firmware
        run: |
          mkdir build-feather
          cd build-feather
          PICO_BOARD=feather_host cmake -DCMAKE_BUILD_TYPE=Release ..
          make c0_passthrough
          cd ..
          mkdir artifacts
          mv build-feather/c0_passthrough.uf2 artifacts/firmware_c0_feather.uf2
        working-directory: ./firmware
      - uses: actions/upload-artifact@v7
        with:
          name: jarvis-c0-feather
          path: firmware/artifacts/firmware_c0_feather.uf2
